version: "3.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=America/Toronto
    volumes:
      - /owncloud/RaspberryPi/ezyArr/docker/sonarr-config:/config
      - /owncloud/RaspberryPi/ezyArr/data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=America/Toronto
    volumes:
      - /owncloud/RaspberryPi/ezyArr/docker/radarr-config:/config
      - /owncloud/RaspberryPi/ezyArr/data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=America/Toronto
    volumes:
      - /owncloud/RaspberryPi/ezyArr/docker/lidarr-config:/config
      - /owncloud/RaspberryPi/ezyArr/data:/data
    ports:
      - "8686:8686"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=America/Toronto
    volumes:
      - /owncloud/RaspberryPi/ezyArr/docker/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=13000
      - UMASK=002
      - TZ=America/Toronto
    volumes:
      - /owncloud/RaspberryPi/ezyArr/docker/jellyfin-config:/config
      - /owncloud/RaspberryPi/ezyArr/data/media:/data
    ports:
      - "8096:8096"
    restart: unless-stopped
    
  qbittorrentvpn:
    privileged: true
    container_name: qbittorrentvpn
    volumes:
      - /owncloud/RaspberryPi/ezyArr/docker/qbittorrent-config:/config
      - /owncloud/RaspberryPi/ezyArr/data/torrents:/data/torrents
    environment:
      - PUID=13005
      - PGID=13000
      - UMASK=002
      - VPN_ENABLED=yes
      - VPN_TYPE=openvpn
      - LAN_NETWORK=10.0.0.0/24

      - DOWNLOAD_DIR_CHOWN=no
      - HEALTH_CHECK_HOST=8.8.8.8
      - HEALTH_CHECK_INTERVAL=50
      - NAME_SERVERS=8.8.8.8,8.8.4.4

      - WEBUI_PORT_ENV=9191
    ports:
      - "9191:8080"
    restart: unless-stopped
    image: trigus42/qbittorrentvpn
  
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - LOG_LEVEL=debug
      - TZ=America/Toronto
    ports:
      - "5055:5055"
    volumes:
      - /owncloud/RaspberryPi/ezyArr/docker/jellyseerr-config:/app/config
    restart: unless-stopped
