version: "3.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /srv/dev-disk-by-uuid-3E7CF7137CF6C4A5/ownCloud/ezyArr/docker/sonarr-config:/config
      - /srv/dev-disk-by-uuid-3E7CF7137CF6C4A5/ownCloud/ezyArr/data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /srv/dev-disk-by-uuid-3E7CF7137CF6C4A5/ownCloud/ezyArr/docker/radarr-config:/config
      - /srv/dev-disk-by-uuid-3E7CF7137CF6C4A5/ownCloud/ezyArr/data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /srv/dev-disk-by-uuid-3E7CF7137CF6C4A5/ownCloud/ezyArr/docker/lidarr-config:/config
      - /srv/dev-disk-by-uuid-3E7CF7137CF6C4A5/ownCloud/ezyArr/data:/data
    ports:
      - "8686:8686"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /srv/dev-disk-by-uuid-3E7CF7137CF6C4A5/ownCloud/ezyArr/docker/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${UID}
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /srv/dev-disk-by-uuid-3E7CF7137CF6C4A5/ownCloud/ezyArr/docker/jellyfin-config:/config
      - /srv/dev-disk-by-uuid-3E7CF7137CF6C4A5/ownCloud/ezyArr/data/media:/data
    ports:
      - "8096:8096"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8080
    volumes:
      - /srv/dev-disk-by-uuid-3E7CF7137CF6C4A5/ownCloud/ezyArr/docker/qbittorrent-config:/config
      - /srv/dev-disk-by-uuid-3E7CF7137CF6C4A5/ownCloud/ezyArr/data/torrents:/data/torrents
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped